#
# Copyright © 2024. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.
#

# name of the pipeline
name: generic-runner
# the namespace that the pipeline will be deployed to
namespace: tekton-tasks
# label indicating which project this pipeline belongs to (Don't change)
partOf: platform-provisioner
# indicating which tools are used to generate this template (Don't change)
createdBy: generator-v2
# the matching label name for GUI to find this pipeline (Don't change)
pipelineConfigLabel: pipeline-gui-config
# the config group for GUI to filter out the pipeline
pipelineConfigGroups:
  all: true
# the api version of the pipeline
pipelineApiVersion: tekton.dev/v1
# pipeline params.
# this is the interface for the pipeline to accept input parameters.
# the pipelinerun template is defined in pipelineConfig.yaml configmap pipelineRun section.
pipelineParams:
  account:
    name: "awsAccount"
  region:
    name: "awsRegion"
    default: "us-west-2"
  input:
    name: "input"
# the docker image that the pipeline will be used to run
pipelineImage: ""
# the shared script configmap name
commonScriptConfigmapName: common-dependency-scripts
# the timeout of pipelinerun
pipelineRunTimeout: 2h
# the timeout of taskrun
taskRunTimeout: 1h55m0s
# the timeout of finally task
finallyTimout: 5m
# the service account that this pipeline will be attached to
serviceAccount: provision

# follow Restricted: https://kubernetes.io/docs/concepts/security/pod-security-standards/
podSecurityContext:
  seccompProfile:
    type: RuntimeDefault  # RuntimeDefault or Localhost (must for Restricted)
  runAsNonRoot: false  # true  # Prevents processes from running as root (both) Container must run as a non-root user (must for Restricted)
  runAsUser: 0  # 1000  # Explicitly set the user ID for running processes (both) (must for restrict, non-zero or undefined/null)
  # runAsGroup: 3000  # Set the group ID for running processes (both)
  # fsGroup: 2000  # Specify the group ID for mounted volumes (pod security context only)
  # fsGroupChangePolicy: OnRootMismatch # Set the policy for the change of fsGroup in the volume (pod security context only)
  # supplementalGroups: [1000,3000]  # Specify the group IDs for running processes (pod security context only)
  # sysctls: {} # Kernel settings to apply (pod security context only)
  # seLinuxOptions: {} # SELinux options to apply (both)
  # windowsOptions: {} # Windows options to apply (both)

# the container and tools need to be ready to run as read-only root filesystem.
securityContext:
  readOnlyRootFilesystem: false  # true  # Prevents the container from writing to the root filesystem (container security context only)
  allowPrivilegeEscalation: false  # Prevents privilege escalation (container security context only) (must for Restricted)
  capabilities:  # Add or drop capabilities (container security context only)
    drop: ["ALL"]  # Drop all capabilities (must for Restricted)
    # add: ["NET_BIND_SERVICE"] # Add the NET_BIND_SERVICE capability to the container (only for lower 1024 ports) (allow for Restricted)
  # privileged: false # Prevents privilege escalation (container security context only) (for Baseline)
  # procMount: Default # Set the mount propagation mode for the container (container security context only)
