#
# Copyright © 2024. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.
#

apiVersion: v2
name: common-dependency
version: "1.0.5"
appVersion: "1.0.0"
description: common-dependency
type: application
home: https://github.com/TIBCOSoftware/tp-helm-charts
maintainers:
  - name: TIBCO Cloud Dev Team
    email: cloud@tibco.com
