#
# Copyright © 2024. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.
#

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "platform-provisioner-ui.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "platform-provisioner-ui.labels" . | nindent 4 }}
data:
  {{ $currentScope := .}}
  {{- range $path, $bytes := .Files.Glob "config/*" }}
  {{ base $path }}: |
    {{- with $currentScope}}
{{ tpl (.Files.Get $path) . | indent 4 }}
    {{- end }}
  {{- end }}