#
# Copyright © 2024. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.
#

{{- if .Values.sso.pem.private }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "platform-provisioner-ui.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "platform-provisioner-ui.labels" . | nindent 4 }}
data:
  sso-private.pem: {{ .Values.sso.pem.private}}
  ta-public.pem: {{ .Values.sso.pem.public}}
type: Opaque
{{- end }}
