#
# Copyright © 2024. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.
#

{{- if .Values.imagePullSecret.create }}
kind: Secret
type: kubernetes.io/dockerconfigjson
apiVersion: v1
metadata:
  name: {{ include "platform-provisioner-ui.fullname" . }}-image-pull
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "platform-provisioner-ui.labels" . | nindent 4 }}
    {{- with .Values.imagePullSecret.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  .dockerconfigjson: {{ .Values.imagePullSecret.secret }}
{{- end }}
