#
# Copyright © 2024. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.
#

apiVersion: v1
kind: Service
metadata:
  name: {{ include "platform-provisioner-ui.fullname" . }}
  labels:
    {{- include "platform-provisioner-ui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "platform-provisioner-ui.selectorLabels" . | nindent 4 }}
