#
# Copyright 2025 Cloud Software Group, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.cloud.tibco.com/created-by: {{ .Values.createdBy }}
    app.kubernetes.io/name: {{ .Values.name }}-config
    app.kubernetes.io/part-of: {{ .Values.partOf }}
    app.kubernetes.io/version: {{ .Chart.Version }}
data:
  {{ $currentScope := .}}
  {{- range $path, $bytes := .Files.Glob "config/*" }}
  {{ base $path }}: |
    {{- with $currentScope}}
{{ tpl (.Files.Get $path) . | indent 4 }}
    {{- end }}
  {{- end }}