#
# Copyright © 2024. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.
#

# Recipe for installing TIBCO Control Plane on-premises
# This recipe provides a basic thrird-party tools that needed for TIBCO Control Plane
# cert-manager
# metrics-server
# ingress-nginx
# postgresql
apiVersion: v1
kind: helm-install
meta:
  globalEnvVariable:
    REPLACE_RECIPE: true
    PIPELINE_LOG_DEBUG: false
    PIPELINE_CHECK_DOCKER_STATUS: false
    # env
    TP_CLUSTER_NAME: ${GUI_TP_CLUSTER_NAME:-"on-prem"}
    # domain
    TP_INSTALL_NGINX_INGRESS: ${GUI_TP_INSTALL_NGINX_INGRESS:-"true"}
    TP_INGRESS_NAMESPACE: ingress-system
    TP_DNS_DOMAIN: ${GUI_TP_DNS_DOMAIN:-"localhost.dataplanes.pro"}
    TP_INGRESS_SERVICE_TYPE: ClusterIP # LoadBalancer used for minikube with tunel, NodePort used for kind, ClusterIP used for kubectl port-forward
    TP_INGRESS_USE_HOSTPORT: false # true for kind
    # storage
    TP_STORAGE_CLASS: ${GUI_TP_STORAGE_CLASS:-"standard"} # hostpath for docker for mac, standard for minikube and kind, microk8s-hostpath for microk8s
    # third party
    TP_EXT_NAMESPACE: tibco-ext
    # CP DB setup env
    TP_INSTALL_POSTGRES: ${GUI_TP_INSTALL_POSTGRES:-"true"}
    TP_DB_USER_NAME: ${GUI_TP_DB_USER_NAME:-"postgres"} # TP_RDS_USERNAME in create-rds.sh
    TP_DB_PASSWORD: ${GUI_TP_DB_PASSWORD:-"postgres"} # TP_RDS_MASTER_PASSWORD in create-rds.sh
    TP_DB_NAME: postgres
    TP_DB_SECRET_NAME: provider-cp-database-credentials # not used
    # flow control
    TP_INSTALL_CERT_MANAGER: true
    TP_INSTALL_METRICS_SERVER: true
  tools:
    yq: "4.40"
    helm: "3.13"
    kubectl: "1.28"
helmCharts:
- condition: ${TP_INSTALL_CERT_MANAGER}
  name: cert-manager
  version: v1.13.2 # release: https://github.com/cert-manager/cert-manager/releases
  repo:
    helm:
      url: https://charts.jetstack.io
  values:
    keepPrevious: true
    content: |
      installCRDs: true
      serviceAccount:
        create: true
        name: cert-manager
  cluster:
    names:
      - ${TP_CLUSTER_NAME}
  releaseName: cert-manager
  namespace: cert-manager
  flags:
    wait: true
    timeout: 1h
    createNamespace: true
- condition: ${TP_INSTALL_METRICS_SERVER}
  name: metrics-server
  version: "3.12.0"
  repo:
    helm:
      url: https://kubernetes-sigs.github.io/metrics-server/
  values:
    keepPrevious: true
    content: |
      clusterName: ${TP_CLUSTER_NAME}
      serviceAccount:
        create: true
        name: metrics-server
      args:
        - "--kubelet-insecure-tls" # https://github.com/docker/for-mac/issues/6274#issuecomment-1259624307
        - "--metric-resolution=90s"
  cluster:
    names:
      - ${TP_CLUSTER_NAME}
  releaseName: metrics-server
  namespace: kube-system
  flags:
    wait: true
    timeout: 1h
    createNamespace: true
- condition: ${TP_INSTALL_NGINX_INGRESS}
  name: ingress-nginx
  namespace: ${TP_INGRESS_NAMESPACE}
  version: 4.10.0 # release: https://github.com/kubernetes/ingress-nginx/releases
  repo:
    helm:
      url: https://kubernetes.github.io/ingress-nginx
  values:
    keepPrevious: true
    content: |
      # ingress-nginx doc: https://docs.nginx.com/nginx-ingress-controller/
      # ingress-nginx chart values: https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/values.yaml
      controller:
        allowSnippetAnnotations: true # https://github.com/kubernetes/ingress-nginx/pull/10393
        hostPort:
          enabled: ${TP_INGRESS_USE_HOSTPORT} # true for kind
        service:
          type: ${TP_INGRESS_SERVICE_TYPE} # NodePort for kind, LoadBalancer for others
        ingressClass:
          - nginx
  cluster:
    names:
      - ${TP_CLUSTER_NAME}
  releaseName: ingress-nginx
  flags:
    wait: true
    timeout: 1h
    createNamespace: true
- name: postgresql
  version: 11.9.13 # 14.3.3 use postgresql 16.2.0, 11.9.13 use postgresql 14.5.0 PCP-4922
  namespace: ${TP_EXT_NAMESPACE}
  releaseName: postgresql
  condition: ${TP_INSTALL_POSTGRES}
  repo:
    helm:
      url: https://charts.bitnami.com/bitnami
  cluster:
    names:
      - ${TP_CLUSTER_NAME}
  values:
    keepPrevious: true
    content: |
      auth:
        postgresPassword: ${TP_DB_PASSWORD}
        username: ${TP_DB_USER_NAME}
        password: ${TP_DB_PASSWORD}
        database: "${TP_DB_NAME}"
      persistence:
        storageClass: ${TP_STORAGE_CLASS}
  flags:
    createNamespace: true
    timeout: 1h
