#
# Copyright 2025 Cloud Software Group, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# this config is used for GUI to find pipeline config
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-config
  namespace: {{ .Values.namespace }}
  labels:
    app.cloud.tibco.com/created-by: {{ .Values.createdBy }}
    app.kubernetes.io/name: {{ .Values.name }}-scripts
    app.kubernetes.io/part-of: {{ .Values.partOf }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    env.cloud.tibco.com/config: {{ .Values.pipelineConfigLabel }}
  annotations:
    env.cloud.tibco.com/config-groups: |
      {{ .Values.pipelineConfigGroups | toJson }}
data:
  config: |
    {{ .Values.name }}:
      name: {{ .Values.name }}-task
      description: |
{{ tpl (.Files.Get "docs/guiConfig.md") . | indent 8 }}
      defaultValue: |
{{ .Files.Get "docs/defaultValue.yaml" | indent 8 }}
      pipelineRun:
        apiVersion: {{ .Values.pipelineApiVersion }}
        kind: PipelineRun
        metadata:
          name: {{ .Values.name }}
          namespace: {{ .Values.namespace }}
          labels:
            env.cloud.tibco.com/name: {{ .Values.name }}
        spec:
          params: []
          timeouts:
            pipeline: "{{ .Values.pipelineRunTimeout }}"
            tasks: "{{ .Values.taskRunTimeout }}"
            finally: "{{ .Values.finallyTimout }}"
          taskRunTemplate:
            serviceAccountName: {{ .Values.serviceAccount }}
            podTemplate:
              securityContext:
                {{- toYaml .Values.podSecurityContext | nindent 16 }}
          pipelineRef:
            name: {{ .Values.name }}

