#
# Copyright © 2024. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.
#

pipelineName: "Deploy Control Plane On-Prem Stack"
description: |
  This pipeline will deploy supporting tools for CP on-prem use case.
  Currently it is tested for kind environment. We have to use github token to access the dev helm charts.
  After the deployment, you will get an email in MailDev to reset the password.
  You need to use port-forward to access MailDev. 
  ```bash
  kubectl port-forward svc/development-mailserver -n tibco-ext 1080:1080
  ```
  Then you can access MailDev at `http://localhost:1080`
options:
- name: "GUI_TP_DNS_DOMAIN"
  type: string
  guiType: input
  reference: "meta.guiEnv.GUI_TP_DNS_DOMAIN"
  description: "The CP DNS domain"
- name: "GUI_TP_STORAGE_CLASS"
  type: string
  guiType: input
  reference: "meta.guiEnv.GUI_TP_STORAGE_CLASS"
  description: "hostpath for docker for mac, standard for minikube and kind, microk8s-hostpath for microk8s"
- name: "GUI_TP_INGRESS_SERVICE_TYPE"
  labels:
    - "ClusterIP"
    - "LoadBalancer"
    - "NodePort"
    - "hostPort"
  values:
    - "ClusterIP"
    - "LoadBalancer"
    - "NodePort"
    - "hostPort"
  type: string
  guiType: radio
  reference: "meta.guiEnv.GUI_TP_INGRESS_SERVICE_TYPE"
- name: "GUI_TP_INGRESS_USE_HOSTPORT"
  type: boolean
  guiType: checkbox
  reference: "meta.guiEnv.GUI_TP_INGRESS_USE_HOSTPORT"
  description: "When deploy on kid we need to use hostport for ingress controller"
recipe: |
{{ .Files.Get "recipes/pp-deploy-cp-tools-on-prem.yaml" | indent 2 }}
