pipelineName: "Data Plane information"
description: |
  This pipeline will undeploy TIBCO Control Plane.
options:
- name: "CP namespace"
  type: string
  guiType: input
  reference: "meta.guiEnv.GUI_CP_NAMESPACE"
  required: true
  description: "The namespace of the CP instance."
recipe: |
  apiVersion: v1
  kind: generic-runner
  meta:
    guiEnv:
      note: "undeploy-cp"
      GUI_PIPELINE_LOG_DEBUG: false
      GUI_CP_NAMESPACE: 'cp1-ns'
    globalEnvVariable:
      REPLACE_RECIPE: true
      PIPELINE_LOG_DEBUG: ${GUI_PIPELINE_LOG_DEBUG:-false}
      PIPELINE_CHECK_DOCKER_STATUS: false
      CP_CLUSTER_NAME: ${GUI_CP_CLUSTER_NAME:-"on-prem"}
      CP_NAMESPACE: ${GUI_CP_NAMESPACE}
  tasks:
    - condition: true
      clusters:
        - name: ${CP_CLUSTER_NAME}
      script:
        ignoreErrors: false
        fileName: script.sh
        content: |
          NS=${CP_NAMESPACE} && \
          kubectl delete -n ${NS} --all tibcoresourceset --ignore-not-found && \
          helm del -n ${NS} \
            platform-base \
            platform-bootstrap \
            --ignore-not-found && \
          kubectl delete namespace ${NS}
