name: Clean up docker image

on: workflow_dispatch
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: platform-provisioner

jobs:
  release-docker:
    name: clean up docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.DELETE_PACKAGE_TOKEN }}
          script: |
            const response = await github.request("GET /orgs/${{ env.OWNER }}/packages/container/${{ env.PACKAGE_NAME }}/versions",
              { per_page: ${{ env.PER_PAGE }}
            });
            for(version of response.data) {
                if (version.metadata.container.tags.length == 0) {
                    console.log("delete " + version.id)
                    const deleteResponse = await github.request("DELETE /orgs/${{ env.OWNER }}/packages/container/${{ env.PACKAGE_NAME }}/versions/" + version.id, { });
                    console.log("status " + deleteResponse.status)
                }
            }
        env:
          OWNER: tibcosoftware # or orgs/<org name>
          PACKAGE_NAME: platform-provisioner%2Fplatform-provisioner
          PER_PAGE: 100
